version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/linnv/bufferlog
    steps:
      - checkout
      - run:
          name: "Get 3th packages"
          command: go get -v -t -d ./...
      - run: 
          name: "Run Test"
          command: go test ./...
